### ISSUE TITLE
Bug: Images not visible in the documentation

### ISSUE THREAD

**Issue by SSHSRN** [gitkraken/gitlens-docs#13]
I was just checking out the GitLens documentation when I noticed that the images are not showing up in many md files.

![image](https://user-images.githubusercontent.com/62781914/197114162-18261565-083a-43b5-b1e5-25e80fa85d49.png)

On checking the image files, I noticed that the path specified in the md files is wrong and that is why the images weren't showing up.

**Comment by SSHSRN** [comment]
Kindly assign me this issue so that I can work on it!

**Comment by Axxzilla** [comment]
Hi @SSHSRN  the images are not intended to work here, this page is meant to be viewed on help.gitkraken.com - go here to see the documentation page: [https://help.gitkraken.com/gitlens/gitlens-account/](https://help.gitkraken.com/gitlens/gitlens-account/)

**Comment by SSHSRN** [comment]
I noticed that too. The images can be seen from the website, but it would be even better if it can be seen from the GitHub directly too.

I made a minor change and it now works.

**Before change:**
* Md:
![image](https://user-images.githubusercontent.com/62781914/197222774-1adaa977-e9f6-451c-b0d9-308df7d79c47.png)
* Preview:
![image](https://user-images.githubusercontent.com/62781914/197222835-1bf8c876-11ef-402a-81e7-ded64d09d898.png)
**After Change:**
* Md:
![image](https://user-images.githubusercontent.com/62781914/197223001-60d5a4bb-1f83-4a66-9254-7bbcda330c02.png)
* Preview:
![image](https://user-images.githubusercontent.com/62781914/197223053-2abbed75-1aa3-4708-9e4c-b47f77c80093.png)
