### ISSUE TITLE
Broken Image Links 

### ISSUE THREAD

**Issue by AnthonyByansi** [gitkraken/gitlens-docs#39]
I've been going through some of the gitlens-docs and I found most of the image links  broken at [Gitlens-account.md](https://github.com/gitkraken/gitlens-docs/blob/main/gitlens/gitlens-account.md#rename-organization)

**Comment by jkelroy** [comment]
Hello @AnthonyByansi, images are not intended to be shown on GitHub. For our documentation, please see the [Help Center](https://help.gitkraken.com/gitlens/gitlens-home/). For example, here is the [Account](https://help.gitkraken.com/gitlens/gitlens-account/) page.
