### ISSUE TITLE
GitHub signup and Purchase Links Inaccessible 

### ISSUE THREAD

**Issue by AnthonyByansi** [gitkraken/gitlens-docs#40]
In the [Sign-up and Purchase section ](https://github.com/gitkraken/gitlens-docs/blob/main/gitlens/gitlens-account.md#sign-up-and-purchase), Links are totally inaccessible and hence  unable to complete the desired tasks.
![issue2](https://github.com/gitkraken/gitlens-docs/assets/101401469/b7991f9c-767e-4146-8067-73f07cd7a3b5)
![gitkraken2](https://github.com/gitkraken/gitlens-docs/assets/101401469/6a5195c8-83fb-4bfd-ba58-7f14260d8478)

**Comment by jkelroy** [comment]
Similar to #39, the [help center](https://help.gitkraken.com/gitlens/gitlens-account/) is where you would want to view this documentation live. Both images and links should are accessible there.
